import os
from dotenv import load_dotenv

# Load .env for secrets
load_dotenv()

# DATA PROVIDER
DATA_PROVIDER = "yfinance"

# Broker / API keys
PROVIDER_API_KEY = os.getenv("PROVIDER_API_KEY", "")
PROVIDER_API_SECRET = os.getenv("PROVIDER_API_SECRET", "")
PROVIDER_ACCESS_TOKEN = os.getenv("PROVIDER_ACCESS_TOKEN", "")

# Telegram
TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
TELEGRAM_CHAT_IDS = []  # start empty; auto-added when users start bot

# Portfolio & money
TOTAL_CAPITAL = 1000000   # ₹10,00,000
STOP_LOSS_PERCENT = 2     # alert if loss >= 2%
PARTIAL_SELL_PERCENT = 25 # partial sell %

# Timezone
TIMEZONE = "Asia/Kolkata"

# NIFTY50 symbols
NIFTY50 = [
    "ADANIENT","ADANIPORTS","APOLLOHOSP","ASIANPAINT","AXISBANK","BAJAJ-AUTO","BAJFINANCE",
    "BAJAJFINSV","BEL","BHARTIARTL","CIPLA","COALINDIA","DRREDDY","EICHERMOT","ETERNAL",
    "GRASIM","HCLTECH","HDFCBANK","HDFCLIFE","HEROMOTOCO","HINDALCO","HINDUNILVR",
    "ICICIBANK","INDUSINDBK","INFY","ITC","JIOFIN","JSWSTEEL","KOTAKBANK","LT","M&M",
    "MARUTI","NESTLEIND","NTPC","ONGC","POWERGRID","RELIANCE","SBILIFE","SHRIRAMFIN",
    "SBIN","SUNPHARMA","TCS","TATACONSUM","TATAMOTORS","TATASTEEL","TECHM","TITAN",
    "TRENT","ULTRACEMCO","WIPRO"
]
